
version: '3'

services:
  ldap:
    build:
      context: .
    ports:
      - 8888:8888
      - 1389:1389
    expose:
      - 8888
      - 1389
    networks:
      default:
        aliases:
         - ldap-hostname.svc
  vulnapp:
    links:
      - ldap
    image: ghcr.io/christophetd/log4shell-vulnerable-app
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      default:
        aliases:
         - app.svc